service: setup-todo
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region:  us-east-1
  iamRoleStatements: 
    - Effect: Allow
      Action:
       - dynamodb:*
      Resource:
       - "arn": process.env.DYNAMODB_TABLE_ARN


functions:
  addTodo:
    handler: src/handler/addTodo.handler
    events:
      - httpApi:
          path: /
          method: post
  fetchTodos:
    handler: src/handler/fetchTodos.handler
    events:
      - httpApi:
          path: /todos
          method: get
  fetchTodo:
    handler: src/handler/fetchTodo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: get
  updateTodo:
    handler: src/handler/updateTodo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: put
resources:
  Resources: 
    TodoTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH 